Add `RHASH_SIZE`
tildeio/libcruby-sys pull request #50
Opened 2018-09-11 19:40 UTC by wagenet

2018-09-13 01:32 UTC, chancancode commented on src/ruby.rs
> +    /// The macro is currently redefined in `internal.h`.
Ah. I just misunderstood your comment. Looking at the [commit](https://github.com/ruby/ruby/commit/8250aa2df0d6b4dcfa11dbad5307d28c2d5dd85f), I believe it is just an implementation detail of the hash class. Basically, the public API version of `RHASH_SIZE` you will be using will be the one defined in ruby.h, so I think we can safely drop this.

2018-09-13 01:34 UTC, chancancode commented on src/ruby.rs
> +    /// The macro is currently redefined in `internal.h`.
(Specifically, it was moving things out of `includes` – which hoses the public-ish APIs into the private header files that you can't link to)

2018-09-13 01:38 UTC, chancancode commented on ext/ruby.c
> +// Should be ok to do ull here.
There are apparently such platforms that _Ruby_ still supports (at least the code still support it). This is something we need a global policy/answer for and blocks #51 as well.

There are a couple of scenarios:

1. Ruby no longer support those platforms/compilers and the code is just bit-rotting. In which case we can safely ignore this every time we see it in the codebase, and should probably PR to ruby/ruby to clean things up.

2. Ruby still support them but we don't care to. In which case we should document that.

3. We both support them. In which case we need to find a better way to do this.

2018-09-13 17:33 UTC, wagenet commented on ext/ruby.c
> +// Should be ok to do ull here.
AFAICT, `long long` does exist on 32-bit C, so this should be safe.

2018-09-13 17:37 UTC, wagenet commented
@chancancode I've addressed both of your concerns.

2018-09-13 19:02 UTC, chancancode requested changes
I think 
https://github.com/tildeio/libcruby-sys/pull/50#discussion_r217238422 is still an outstanding question. Ruby seems to think that there are supported C compilers in-use that would barf on `unsigned long long`, or otherwise have the "wrong" size that it needs to. (Also this may actually want to be a `libc::size_t`.) I self-assigned for the investigation.

2018-09-14 22:28 UTC, chancancode approved these changes
we confirmed this is supposed to return a `size_t`

2018-09-14 23:13 UTC, merged